name: Repo-Variable-Demo
on: [push]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Repo Name=$GITHUB_REPOSITORY"
          echo "Commit ID is=$GITHUB_SHA"
          echo "Actor=$GITHUB_ACTOR"
